# Generated by Django 2.1.3 on 2019-01-06 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quality', models.IntegerField(max_length=3)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2019, 1, 6, 12, 26, 58, 240867, tzinfo=utc))),
            ],
        ),
    ]
