# Generated by Django 2.1.3 on 2019-01-06 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diuration', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 13, 37, 26, 346394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='quality',
            field=models.IntegerField(),
        ),
    ]
