# Generated by Django 2.1.3 on 2019-01-06 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_auto_20190106_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('level', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='diuration',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 14, 5, 27, 678525, tzinfo=utc)),
        ),
    ]
