# Generated by Django 2.1.3 on 2019-01-06 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0007_auto_20190106_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='duration',
            new_name='diuration',
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 14, 22, 32, 122774, tzinfo=utc)),
        ),
    ]
