# Generated by Django 2.1.3 on 2019-01-11 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0011_auto_20190111_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfilio',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfilio',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 19, 52, 54, 89861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='social_network',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
