# Generated by Django 2.1.3 on 2019-01-12 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0013_auto_20190112_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 19, 37, 8, 378297, tzinfo=utc)),
        ),
    ]
