# Generated by Django 2.1.3 on 2019-02-16 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0017_auto_20190216_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_network',
            name='icon',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 15, 13, 29, 27938, tzinfo=utc)),
        ),
    ]
